name: Build docker images for release
on:
  push:
    branches:
      - main

env:
  IMAGE_BACKEND_NAME: 'outline'
  APP_BACKEND_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Register variables
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
          echo 
      - name: Checkout git repo
        uses: actions/checkout@v2
        
      - name: Setup QEMU for docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.APP_BACKEND_PATH }}
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_BACKEND_NAME }}:latest
            ghcr.io/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_BACKEND_NAME }}:${{ github.run_number }}
          push: true
